# Generated by Django 4.2.9 on 2024-01-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('imag', models.ImageField(upload_to='pics')),
                ('des', models.TextField()),
            ],
        ),
    ]
